//-----GET------//

export const GET_USERS = "GET_USERS";
//DONE!

export const GET_USER_BY_GENDER = "GET_USER_BY_GENDER";
//PRIORIDAD ALTA
//DONE!

export const GET_USER_BY_GENDERINT = "GET_USER_BY_GENDERINT"
//DONE!

export const GET_USER_BY_ID = "GET_USER_BY_ID";


export const GET_USER_LIKES = "GET_USER_LIKES"; //USING ID
//PRIORIDA ALTA

export const GET_USER_MATCHES = "GET_USER_MATCHES"; //USING ID
//PRIORIDAD ALTA

//-----FILTERS & SORTERS------//

export const FILTER_BY_HENRYLVL = "FILTER_BY_HENRYLVL";
//===> ETAPA DEL BOOTCAMP (CHALLENGE, M1, M2, M3, M4 PI, PF, GRADUATED)
//PRIORIDAD MEDIA

export const FILTER_BY_INTEREST = "FILTER_BY_INTEREST";
//====>ARTUR: EN LA DB DEBEMOS TENER UNAS OPCIONES DE INTERESES (MARTIN DIJO QUE UNAS 50  *O.O*  EN PRINCIPIO UNAS 20 DIRIA YO HASTA RESOLVER COMO SE RENDERIZARAN)
//COMIDA, SALIR A COMER, PIZZA, CINE, NETFLIX, MUSICA, BAILAR, VIAJAR, SHOPPING, PESCA, GYM, JUEGOS DE MESA, VIDEOGAMES, KARAOKE, LEER, AUDIOLIBROS, RUNNING, DOCUMENTALES, SERIES...
//PRIORIDAD MEDIA

export const SORT_BY_AGE = "SORT_BY_AGE";
//PRIORIDAD MEDIA

//-----CREATE (POST)------//

export const CREATE_USER = "CREATE_USER";
//PRIORIDAD ALTA

//-----UPDATE (PUT)------//

export const UPDATE_USER = "PUT_USER";
//PRIORIDAD ALTA

/* 
STORE-REDUX

const initialState = {
  users: [],
  usersToWork: [], //USADO PARA FILTERS & SORTERS 
  userDetail: [], //USADO TAMBIEN PARA CLEAR_USER_DETAIL
  
  OPCIONALES?   
  message: [],
  gender: [],
}; 
*/
//-----STATES------//
//
export const CLEAR_USER_DETAIL = "CLEAR_USER_DETAIL";

//CLEAR_MESSAGE
